[expt]
blank = 'No'

# Blanks:
[well.'A1,H1,A12,H12']
blank = 'Yes'

# Substances
[block.9x4]
A1.sample = 'Substance_1'
E1.sample = 'Substance_2'

[block.3x8]
A10.sample = 'Control'

# Concetration
[col.'1,2,3']
conc_uM = '100'

[col.'4,5,6']
conc_uM  = '10'

[col.'7,8,9']
conc_uM  = '1'

[col.'10,11,12']
conc_uM  = '0'











